/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.nh;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class UsingProducers {

    private static final Logger LOG = LoggerFactory.getLogger(UsingProducers.class);

    public static void main(String[] args) {
        LOG.info("Using producers");


    }
}
